# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: curve_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='curve_data.proto',
  package='sdk_curve',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x63urve_data.proto\x12\tsdk_curve\"D\n\x08\x43urveCal\x12)\n\x06method\x18\x01 \x01(\x0e\x32\x19.sdk_curve.CurveCalMethod\x12\r\n\x05value\x18\x02 \x01(\x01\"\x96\x02\n\tCurveData\x12\x10\n\x08\x61pp_mark\x18\x01 \x01(\t\x12\x31\n\x07tag_set\x18\x02 \x03(\x0b\x32 .sdk_curve.CurveData.TagSetEntry\x12\x37\n\nmetric_val\x18\x03 \x03(\x0b\x32#.sdk_curve.CurveData.MetricValEntry\x12\x15\n\rinstance_mark\x18\x04 \x01(\t\x1a-\n\x0bTagSetEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x45\n\x0eMetricValEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.sdk_curve.CurveCal:\x02\x38\x01\"V\n\x0bSDKCurvePkg\x12)\n\x0b\x63urve_datas\x18\x01 \x03(\x0b\x32\x14.sdk_curve.CurveData\x12\x0b\n\x03seq\x18\x02 \x01(\x03\x12\x0f\n\x07version\x18\x03 \x01(\t*J\n\x0e\x43urveCalMethod\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\x07\n\x03\x41VG\x10\x02\x12\x07\n\x03MAX\x10\x03\x12\x07\n\x03MIN\x10\x04\x12\n\n\x06MIDDLE\x10\x05\x62\x06proto3')
)

_CURVECALMETHOD = _descriptor.EnumDescriptor(
  name='CurveCalMethod',
  full_name='sdk_curve.CurveCalMethod',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AVG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAX', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIN', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIDDLE', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=470,
  serialized_end=544,
)
_sym_db.RegisterEnumDescriptor(_CURVECALMETHOD)

CurveCalMethod = enum_type_wrapper.EnumTypeWrapper(_CURVECALMETHOD)
NONE = 0
ADD = 1
AVG = 2
MAX = 3
MIN = 4
MIDDLE = 5



_CURVECAL = _descriptor.Descriptor(
  name='CurveCal',
  full_name='sdk_curve.CurveCal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='sdk_curve.CurveCal.method', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='sdk_curve.CurveCal.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=99,
)


_CURVEDATA_TAGSETENTRY = _descriptor.Descriptor(
  name='TagSetEntry',
  full_name='sdk_curve.CurveData.TagSetEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='sdk_curve.CurveData.TagSetEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='sdk_curve.CurveData.TagSetEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=309,
)

_CURVEDATA_METRICVALENTRY = _descriptor.Descriptor(
  name='MetricValEntry',
  full_name='sdk_curve.CurveData.MetricValEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='sdk_curve.CurveData.MetricValEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='sdk_curve.CurveData.MetricValEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=380,
)

_CURVEDATA = _descriptor.Descriptor(
  name='CurveData',
  full_name='sdk_curve.CurveData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_mark', full_name='sdk_curve.CurveData.app_mark', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag_set', full_name='sdk_curve.CurveData.tag_set', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metric_val', full_name='sdk_curve.CurveData.metric_val', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instance_mark', full_name='sdk_curve.CurveData.instance_mark', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CURVEDATA_TAGSETENTRY, _CURVEDATA_METRICVALENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=380,
)


_SDKCURVEPKG = _descriptor.Descriptor(
  name='SDKCurvePkg',
  full_name='sdk_curve.SDKCurvePkg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='curve_datas', full_name='sdk_curve.SDKCurvePkg.curve_datas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seq', full_name='sdk_curve.SDKCurvePkg.seq', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='sdk_curve.SDKCurvePkg.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=468,
)

_CURVECAL.fields_by_name['method'].enum_type = _CURVECALMETHOD
_CURVEDATA_TAGSETENTRY.containing_type = _CURVEDATA
_CURVEDATA_METRICVALENTRY.fields_by_name['value'].message_type = _CURVECAL
_CURVEDATA_METRICVALENTRY.containing_type = _CURVEDATA
_CURVEDATA.fields_by_name['tag_set'].message_type = _CURVEDATA_TAGSETENTRY
_CURVEDATA.fields_by_name['metric_val'].message_type = _CURVEDATA_METRICVALENTRY
_SDKCURVEPKG.fields_by_name['curve_datas'].message_type = _CURVEDATA
DESCRIPTOR.message_types_by_name['CurveCal'] = _CURVECAL
DESCRIPTOR.message_types_by_name['CurveData'] = _CURVEDATA
DESCRIPTOR.message_types_by_name['SDKCurvePkg'] = _SDKCURVEPKG
DESCRIPTOR.enum_types_by_name['CurveCalMethod'] = _CURVECALMETHOD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CurveCal = _reflection.GeneratedProtocolMessageType('CurveCal', (_message.Message,), {
  'DESCRIPTOR' : _CURVECAL,
  '__module__' : 'curve_data_pb2'
  # @@protoc_insertion_point(class_scope:sdk_curve.CurveCal)
  })
_sym_db.RegisterMessage(CurveCal)

CurveData = _reflection.GeneratedProtocolMessageType('CurveData', (_message.Message,), {

  'TagSetEntry' : _reflection.GeneratedProtocolMessageType('TagSetEntry', (_message.Message,), {
    'DESCRIPTOR' : _CURVEDATA_TAGSETENTRY,
    '__module__' : 'curve_data_pb2'
    # @@protoc_insertion_point(class_scope:sdk_curve.CurveData.TagSetEntry)
    })
  ,

  'MetricValEntry' : _reflection.GeneratedProtocolMessageType('MetricValEntry', (_message.Message,), {
    'DESCRIPTOR' : _CURVEDATA_METRICVALENTRY,
    '__module__' : 'curve_data_pb2'
    # @@protoc_insertion_point(class_scope:sdk_curve.CurveData.MetricValEntry)
    })
  ,
  'DESCRIPTOR' : _CURVEDATA,
  '__module__' : 'curve_data_pb2'
  # @@protoc_insertion_point(class_scope:sdk_curve.CurveData)
  })
_sym_db.RegisterMessage(CurveData)
_sym_db.RegisterMessage(CurveData.TagSetEntry)
_sym_db.RegisterMessage(CurveData.MetricValEntry)

SDKCurvePkg = _reflection.GeneratedProtocolMessageType('SDKCurvePkg', (_message.Message,), {
  'DESCRIPTOR' : _SDKCURVEPKG,
  '__module__' : 'curve_data_pb2'
  # @@protoc_insertion_point(class_scope:sdk_curve.SDKCurvePkg)
  })
_sym_db.RegisterMessage(SDKCurvePkg)


_CURVEDATA_TAGSETENTRY._options = None
_CURVEDATA_METRICVALENTRY._options = None
# @@protoc_insertion_point(module_scope)
